# Generated by Django 3.0.5 on 2020-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veekprojects', '0003_auto_20200515_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='google.com', max_length=200),
            preserve_default=False,
        ),
    ]
