# Generated by Django 2.2.10 on 2020-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veekprojects', '0005_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('aborted', 'aborted')], default='complete', max_length=9),
        ),
    ]
