# Generated by Django 2.2.10 on 2020-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veekprojects', '0006_auto_20200519_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('aborted', 'aborted')], default='completed', max_length=9),
        ),
    ]
