# Generated by Django 2.1.15 on 2020-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veekprojects', '0009_auto_20200902_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='veekportfolio/profile_pic/'),
        ),
    ]
