# Generated by Django 2.1.15 on 2020-12-04 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veekprojects', '0010_auto_20201204_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
